FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIPENV_VENV_IN_PROJECT 1
# Super User Variables
ENV DJANGO_SUPERUSER_PASSWORD="password"
ENV DJANGO_SUPERUSER_USERNAME="John"
ENV DJANGO_SUPERUSER_EMAIL="test@gmail.com"

WORKDIR /usr/src/app
# Install pipenv
RUN pip install --upgrade pip && pip install pipenv
# Copy the Pipfile and Pipfile.lock into the container at /usr/src/app/
COPY Pipfile Pipfile.lock /usr/src/app/
# Install any needed packages specified in Pipfile
RUN pipenv install --deploy --ignore-pipfile
# Copy the rest of the application's code
COPY . /usr/src/app/
# Make port 8000 available to the world outside this container
EXPOSE 8000
# Before running the application, apply migrations
RUN pipenv run python manage.py migrate
RUN pipenv run python manage.py createsuperuser --noinput
# Start gunicorn
CMD ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
