version: '3.9'

services:
  django:
    build: .
    ports:
      - 8000:8000
    networks:
      - elastic

  elasticsearch:
    container_name: es-01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=true
      - bootstrap.memory_lock=false
      - ELASTIC_PASSWORD=password
      - discovery.type=single-node
    volumes:
      - data-01:/usr/share/elasticsearch/data
      - ./ELK/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./ELK/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  data-01:
    driver: local

networks:
  elastic:
    driver: bridge
