# Default configuration from 
# https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml

cluster.name: "docker-cluster"
network.host: 0.0.0.0

xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true  # Required for Elastic Fleet